version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "28017:27017"

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    volumes:
      - ./backend:/app  
      - /app/node_modules  
    command: npm run start:dev  

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app  
      - /app/node_modules  
    command: npm start -- --host 0.0.0.0
