version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "28017:27017"

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
